from __future__ import annotations

import argparse
import os
import time
from typing import Dict, List, Tuple


def _remove_unsupported_socks_proxy_env() -> None:
    """Remove malformed ``socks://`` proxy variables before importing Gradio.

    HTTPX accepts ``socks5://`` when its optional SOCKS dependency is installed,
    but it rejects the non-standard ``socks://`` scheme during import. This
    annotation application only serves local files, so ignoring only those
    malformed proxy variables is the safest default and does not modify the
    user's shell environment outside this Python process.
    """
    proxy_names = (
        "ALL_PROXY",
        "all_proxy",
        "HTTP_PROXY",
        "http_proxy",
        "HTTPS_PROXY",
        "https_proxy",
    )
    removed = []
    for name in proxy_names:
        value = os.environ.get(name, "").strip()
        if value.lower().startswith("socks://"):
            removed.append(f"{name}={value}")
            os.environ.pop(name, None)

    if removed:
        print(
            "[Proxy] 已忽略 HTTPX 不支持的 socks:// 代理变量："
            + ", ".join(removed)
        )


_remove_unsupported_socks_proxy_env()

import gradio as gr

from annotation_core.config import load_config
from annotation_core.dataset import MANIFEST_SCHEMA_VERSION, load_jsonl
from annotation_core.render import render_sample_assets
from annotation_core.storage import (
    append_annotation,
    choose_next_index,
    load_latest_annotations,
    sanitize_annotator_id,
)


NO_ATTENTION_VALUE = "__NO_ATTENTION__"
UNCERTAIN_VALUE = "__UNCERTAIN__"
NO_ATTENTION_LABEL = "没有需要重点关注的对象"
UNCERTAIN_LABEL = "画面信息不足，无法判断"
EXPECTED_HISTORY_FRAMES = 40
EXPECTED_FUTURE_FRAMES = 0


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="关键 Actor 人工盲评标注界面")
    parser.add_argument("--config", required=True, help="YAML 配置文件")
    parser.add_argument("--annotator-id", default="", help="可选：预填标注员编号")
    parser.add_argument("--host", default=None, help="覆盖 app.host")
    parser.add_argument("--port", type=int, default=None, help="覆盖 app.port")
    parser.add_argument("--share", action="store_true", help="启用 Gradio share")
    return parser.parse_args()


def _attention_choices(sample: Dict) -> List[Tuple[str, str]]:
    choices = [
        (str(actor["display_label"]), str(actor["display_label"]))
        for actor in sample.get("candidates", [])
    ]
    choices.extend(
        [
            (NO_ATTENTION_LABEL, NO_ATTENTION_VALUE),
            (UNCERTAIN_LABEL, UNCERTAIN_VALUE),
        ]
    )
    return choices


def _previous_selection(record: Dict) -> List[str]:
    selected = [str(value) for value in record.get("selected_display_labels", []) if str(value)]
    if selected:
        return selected

    status = str(record.get("attention_status", "")).strip().lower()
    if status == "none":
        return [NO_ATTENTION_VALUE]
    if status == "uncertain":
        return [UNCERTAIN_VALUE]

    # Compatibility with trial annotations generated by the earlier interface.
    legacy_judgement = str(record.get("scene_judgement", ""))
    if legacy_judgement == "无关键对象":
        return [NO_ATTENTION_VALUE]
    if legacy_judgement == "无法判断":
        return [UNCERTAIN_VALUE]
    return []


def build_app(config_path: str, default_annotator_id: str = "") -> gr.Blocks:
    config = load_config(config_path)
    samples = load_jsonl(config.dataset.manifest_path)
    if not samples:
        raise RuntimeError(
            f"manifest 为空或不存在：{config.dataset.manifest_path}\n"
            "请先运行 prepare_samples.py。"
        )
    if any(
        int(sample.get("schema_version", 0)) != MANIFEST_SCHEMA_VERSION
        or int(sample.get("history_frames", -1)) != EXPECTED_HISTORY_FRAMES
        or int(sample.get("future_frames", -1)) != EXPECTED_FUTURE_FRAMES
        or int(sample.get("center_frame_offset", -1)) != EXPECTED_HISTORY_FRAMES
        or int(sample.get("center_frame_offset", -1)) != len(sample.get("frames", [])) - 1
        for sample in samples
    ):
        raise RuntimeError(
            "检测到不是‘约 4 秒历史画面，并在当前时刻结束’布局的 manifest。\n"
            "请确认 config.yaml 中设置：\n"
            "  sampling.history_frames: 40\n"
            "  sampling.future_frames: 0\n"
            "然后删除旧 manifest 并重新运行：\n"
            "  python prepare_samples.py --config config.yaml"
        )

    sample_ids = {str(sample["sample_id"]) for sample in samples}

    def _completed_sample_count(annotator_id: str) -> int:
        latest = load_latest_annotations(config.dataset.annotation_dir, annotator_id)
        return sum(sample_id in latest for sample_id in sample_ids)

    def _completion_status(last_message: str = "") -> str:
        details = f"{last_message}\n\n" if last_message else ""
        return (
            "## ✅ 全部标注完成\n"
            f"{details}当前标注任务中的 **{len(samples)}/{len(samples)}** 个样本均已处理，"
            "标注结果已经保存。你可以关闭页面，或使用“上一条”回看并修订已有标注。"
        )

    def _progress(index: int, annotator_id: str) -> str:
        if not annotator_id.strip():
            return f"样本总数：**{len(samples)}**。请先输入标注员编号并开始。"
        completed = _completed_sample_count(annotator_id)
        if completed >= len(samples):
            return f"## ✅ 标注任务已完成　｜　进度：**{len(samples)}/{len(samples)}**"
        return (
            f"进度：**{completed}/{len(samples)}**　｜　"
            f"当前序号：**{index + 1}/{len(samples)}**"
        )

    def _sample_metadata(sample: Dict) -> str:
        truncated = int(sample.get("candidate_filter_stats", {}).get("truncated", 0))
        warning = ""
        if truncated:
            warning = f"　｜　⚠ 距离筛选后仍有 {truncated} 个对象因候选上限未展示"
        return (
            f"样本：`{sample['sample_id']}`　｜　路线：`{sample.get('route_name', '')}`"
            f"　｜　中心帧：`{sample.get('center_stem', '')}`{warning}"
        )

    def _form_values(sample: Dict, annotator_id: str) -> Tuple:
        previous = load_latest_annotations(config.dataset.annotation_dir, annotator_id).get(
            sample["sample_id"]
        )
        choices = _attention_choices(sample)
        if previous:
            return (
                gr.update(choices=choices, value=_previous_selection(previous)),
                int(previous.get("confidence", 3) or 3),
                previous.get("notes", ""),
                "已加载该样本此前的标注；再次提交会保存为新修订。",
            )
        return (
            gr.update(choices=choices, value=[]),
            3,
            "",
            "请先观看历史短片；视频最后一帧就是当前判断时刻，再根据当前时刻 Top RGB 中的匿名编号作答。",
        )

    def load_sample(index: int, annotator_id: str):
        try:
            annotator_id = sanitize_annotator_id(annotator_id)
        except ValueError as exc:
            return (
                index,
                time.time(),
                "",
                None,
                None,
                None,
                [],
                gr.update(choices=[], value=[]),
                3,
                "",
                f"错误：{exc}",
                f"样本总数：**{len(samples)}**。",
            )

        index = min(max(int(index), 0), len(samples) - 1)
        sample = samples[index]
        assets = render_sample_assets(sample, config)
        form = _form_values(sample, annotator_id)
        return (
            index,
            time.time(),
            _sample_metadata(sample),
            assets["video"] or None,
            assets["current"],
            assets["top"],
            assets["table"],
            *form,
            _progress(index, annotator_id),
        )

    def start_session(annotator_id: str):
        try:
            annotator_id = sanitize_annotator_id(annotator_id)
        except ValueError as exc:
            return (
                0,
                time.time(),
                "",
                None,
                None,
                None,
                [],
                gr.update(choices=[], value=[]),
                3,
                "",
                f"错误：{exc}",
                f"样本总数：**{len(samples)}**。",
            )
        if _completed_sample_count(annotator_id) >= len(samples):
            result = list(load_sample(len(samples) - 1, annotator_id))
            result[10] = _completion_status()
            result[11] = _progress(len(samples) - 1, annotator_id)
            return tuple(result)

        index = choose_next_index(samples, config.dataset.annotation_dir, annotator_id, 0)
        return load_sample(index, annotator_id)

    def validate_answer(sample: Dict, selected_values: List[str]) -> str:
        valid_labels = {
            str(actor["display_label"]) for actor in sample.get("candidates", [])
        }
        values = [str(value) for value in selected_values or []]
        if not values:
            return "请选择一个或多个 Actor，或者选择“没有需要重点关注的对象/无法判断”。"

        selected_special = {
            value for value in values if value in {NO_ATTENTION_VALUE, UNCERTAIN_VALUE}
        }
        selected_actors = [value for value in values if value not in selected_special]
        if any(label not in valid_labels for label in selected_actors):
            return "选择中包含当前样本不存在的候选编号。"
        if len(selected_special) > 1:
            return "“没有需要重点关注的对象”和“无法判断”不能同时选择。"
        if selected_special and selected_actors:
            return "选择特殊选项时，请取消所有 Actor 编号。"
        return ""

    def submit_and_next(
        index: int,
        started_at: float,
        annotator_id: str,
        selected_values: List[str],
        confidence: int,
        notes: str,
    ):
        try:
            annotator_id = sanitize_annotator_id(annotator_id)
        except ValueError as exc:
            result = list(load_sample(index, annotator_id))
            result[-2] = f"错误：{exc}"
            return tuple(result)

        index = min(max(int(index), 0), len(samples) - 1)
        sample = samples[index]
        error = validate_answer(sample, selected_values)
        if error:
            result = list(load_sample(index, annotator_id))
            result[7] = gr.update(
                choices=_attention_choices(sample),
                value=selected_values or [],
            )
            result[8] = confidence
            result[9] = notes
            result[10] = f"未保存：{error}"
            result[1] = started_at
            return tuple(result)

        values = [str(value) for value in selected_values or []]
        if NO_ATTENTION_VALUE in values:
            attention_status = "none"
            actor_labels: List[str] = []
        elif UNCERTAIN_VALUE in values:
            attention_status = "uncertain"
            actor_labels = []
        else:
            attention_status = "actors"
            actor_labels = values

        by_label = {
            str(actor["display_label"]): actor for actor in sample.get("candidates", [])
        }
        selected = [by_label[label] for label in actor_labels]
        record = {
            "sample_id": sample["sample_id"],
            "route_name": sample.get("route_name", ""),
            "center_stem": sample.get("center_stem", ""),
            "attention_status": attention_status,
            "selected_display_labels": actor_labels,
            "selected_actor_ids": [str(actor["actor_id"]) for actor in selected],
            "selected_actor_classes": [str(actor["class"]) for actor in selected],
            "confidence": int(confidence),
            "notes": notes.strip(),
            "annotation_time_s": round(max(0.0, time.time() - float(started_at)), 3),
            "is_skipped": False,
            "skip_reason": "",
        }
        append_annotation(config.dataset.annotation_dir, annotator_id, record)
        if _completed_sample_count(annotator_id) >= len(samples):
            result = list(load_sample(index, annotator_id))
            result[10] = _completion_status(
                f"已保存最后一条样本 `{sample['sample_id']}`。"
            )
            result[11] = _progress(index, annotator_id)
            return tuple(result)

        next_index = choose_next_index(
            samples,
            config.dataset.annotation_dir,
            annotator_id,
            start_index=index + 1,
        )
        result = list(load_sample(next_index, annotator_id))
        result[10] = f"已保存 `{sample['sample_id']}`，进入下一条未完成样本。"
        return tuple(result)

    def skip_and_next(index: int, started_at: float, annotator_id: str, notes: str):
        annotator_id = sanitize_annotator_id(annotator_id)
        index = min(max(int(index), 0), len(samples) - 1)
        sample = samples[index]
        append_annotation(
            config.dataset.annotation_dir,
            annotator_id,
            {
                "sample_id": sample["sample_id"],
                "route_name": sample.get("route_name", ""),
                "center_stem": sample.get("center_stem", ""),
                "attention_status": "skip",
                "selected_display_labels": [],
                "selected_actor_ids": [],
                "selected_actor_classes": [],
                "confidence": None,
                "notes": notes.strip(),
                "annotation_time_s": round(max(0.0, time.time() - float(started_at)), 3),
                "is_skipped": True,
                "skip_reason": notes.strip() or "人工跳过",
            },
        )
        if _completed_sample_count(annotator_id) >= len(samples):
            result = list(load_sample(index, annotator_id))
            result[10] = _completion_status(
                f"最后一条样本 `{sample['sample_id']}` 已跳过。"
            )
            result[11] = _progress(index, annotator_id)
            return tuple(result)

        next_index = choose_next_index(
            samples,
            config.dataset.annotation_dir,
            annotator_id,
            start_index=index + 1,
        )
        result = list(load_sample(next_index, annotator_id))
        result[10] = f"已跳过 `{sample['sample_id']}`。"
        return tuple(result)

    def previous_sample(index: int, annotator_id: str):
        return load_sample(max(0, int(index) - 1), annotator_id)

    def next_sample_without_save(index: int, annotator_id: str):
        return load_sample(min(len(samples) - 1, int(index) + 1), annotator_id)

    with gr.Blocks(title=config.app.title) as demo:
        gr.Markdown(
            "# 关键 Actor 人工盲评标注\n"
            "视频只展示当前时刻之前约 4 秒的历史，最后一帧就是当前判断时刻，"
            "不包含当前时刻之后的未来画面。界面不会显示 LG 的选择结果。"
        )
        with gr.Row():
            annotator_id = gr.Textbox(
                label="标注员编号",
                value=default_annotator_id,
                placeholder="例如 P01",
                scale=3,
            )
            start_button = gr.Button("开始 / 继续", variant="primary", scale=1)
        progress = gr.Markdown(f"样本总数：**{len(samples)}**。请先开始。")
        sample_meta = gr.Markdown()

        context_video = gr.Video(
            label="连续六视角历史场景（约 4 秒；最后一帧为当前判断时刻）",
            autoplay=False,
        )
        with gr.Row():
            current_image = gr.Image(label="当前时刻六视角（视频最后一帧）", type="filepath")
            top_image = gr.Image(label="当前时刻 Top RGB（匿名候选编号）", type="filepath")

        candidate_df = gr.Dataframe(
            headers=["编号", "类别", "前向 x/m", "右向 y/m", "距离/m", "速度/(m/s)"],
            datatype=["str", "str", "str", "str", "str", "str"],
            interactive=False,
            visible=config.app.show_candidate_table,
            label="候选对象信息（编号已随机化，不代表距离排序）",
        )

        gr.Markdown(
            "## 标注问题\n"
            "> **视频结束时刻就是当前判断时刻。** 请根据此前约 4 秒的场景变化，"
            "选择从当前时刻开始的接下来约 2 秒内，你会**重点关注，"
            "并且可能影响你驾驶判断或操作**的交通参与者。可以选择一个或多个。\n\n"
            "> 仅仅出现在画面中、但不会影响你驾驶判断的对象不需要选择。"
            "红绿灯、道路结构和交通规则本身不属于 Actor。"
        )
        selected_values = gr.CheckboxGroup(
            [],
            label=(
                "1. 请选择当前时刻之后约 2 秒内需要重点关注的 Actor；若没有或无法判断，选择列表末尾的对应选项"
            ),
        )
        confidence = gr.Slider(
            1,
            5,
            value=3,
            step=1,
            label="2. 你对本次选择的置信度（1 低—5 高）",
        )
        notes = gr.Textbox(
            label="备注（可选；跳过时可填写原因）",
            lines=2,
            visible=config.app.allow_notes,
        )
        status = gr.Markdown("请先观看场景。")

        with gr.Row():
            previous_button = gr.Button("上一条")
            skip_button = gr.Button("跳过")
            next_button = gr.Button("下一条（不保存）")
            submit_button = gr.Button("保存并进入下一条", variant="primary")

        index_state = gr.State(0)
        started_at_state = gr.State(time.time())

        outputs = [
            index_state,
            started_at_state,
            sample_meta,
            context_video,
            current_image,
            top_image,
            candidate_df,
            selected_values,
            confidence,
            notes,
            status,
            progress,
        ]

        start_button.click(start_session, inputs=[annotator_id], outputs=outputs)
        previous_button.click(
            previous_sample,
            inputs=[index_state, annotator_id],
            outputs=outputs,
        )
        next_button.click(
            next_sample_without_save,
            inputs=[index_state, annotator_id],
            outputs=outputs,
        )
        submit_button.click(
            submit_and_next,
            inputs=[
                index_state,
                started_at_state,
                annotator_id,
                selected_values,
                confidence,
                notes,
            ],
            outputs=outputs,
        )
        skip_button.click(
            skip_and_next,
            inputs=[index_state, started_at_state, annotator_id, notes],
            outputs=outputs,
        )

        if default_annotator_id.strip():
            demo.load(start_session, inputs=[annotator_id], outputs=outputs)

    return demo


def main() -> None:
    args = parse_args()
    config = load_config(args.config)
    demo = build_app(args.config, args.annotator_id)
    host = args.host or config.app.host
    port = args.port or config.app.port
    share = bool(args.share or config.app.share)
    demo.queue(default_concurrency_limit=8).launch(
        server_name=host,
        server_port=port,
        share=share,
        allowed_paths=[str(config.dataset.work_dir), str(config.dataset.dataset_root)],
    )


if __name__ == "__main__":
    main()
