from __future__ import annotations

import csv
import gzip
import json
from collections import Counter, defaultdict
from itertools import combinations
from pathlib import Path
from typing import Any, Dict, List, Optional, Sequence, Set, Tuple


STATUS_ACTORS = "actors"
STATUS_NONE = "none"
STATUS_UNCERTAIN = "uncertain"
STATUS_SKIP = "skip"
STATUS_INVALID = "invalid"


def read_json_or_jsonl(path: Path) -> List[Dict[str, Any]]:
    opener = gzip.open if path.name.endswith(".gz") else open
    mode = "rt" if path.name.endswith(".gz") else "r"
    with opener(path, mode, encoding="utf-8") as f:  # type: ignore[arg-type]
        text = f.read()
    stripped = text.lstrip()
    if not stripped:
        return []
    if stripped.startswith("["):
        data = json.loads(text)
        return [item for item in data if isinstance(item, dict)]
    if stripped.startswith("{") and "\n" not in stripped.rstrip("\n"):
        data = json.loads(text)
        if isinstance(data, dict):
            for key in ["records", "samples", "predictions", "annotations"]:
                if isinstance(data.get(key), list):
                    return [item for item in data[key] if isinstance(item, dict)]
            return [data]
    records = []
    for line in text.splitlines():
        line = line.strip()
        if line:
            item = json.loads(line)
            if isinstance(item, dict):
                records.append(item)
    return records


def read_annotation_dir(annotation_dir: Path) -> List[Dict[str, Any]]:
    records: List[Dict[str, Any]] = []
    for path in sorted(annotation_dir.glob("annotations_*.jsonl")):
        # Keep only the latest revision for each annotator/sample in each file.
        latest: Dict[Tuple[str, str], Dict[str, Any]] = {}
        for record in read_json_or_jsonl(path):
            key = (
                str(record.get("annotator_id", path.stem)),
                str(record.get("sample_id", "")),
            )
            if key[1]:
                latest[key] = record
        records.extend(latest.values())
    return records


def _string_list(value: Any) -> List[str]:
    if isinstance(value, (list, tuple, set)):
        return [str(item) for item in value if str(item)]
    if isinstance(value, str):
        return [item for item in value.split("|") if item]
    return []


def selected_actor_ids(record: Dict[str, Any]) -> List[str]:
    return _string_list(record.get("selected_actor_ids", []))


def annotation_status(record: Dict[str, Any]) -> str:
    if record.get("is_skipped", False):
        return STATUS_SKIP

    status = str(record.get("attention_status", "")).strip().lower()
    status_aliases = {
        "actors": STATUS_ACTORS,
        "actor": STATUS_ACTORS,
        "selected": STATUS_ACTORS,
        "none": STATUS_NONE,
        "no_actor": STATUS_NONE,
        "no_attention": STATUS_NONE,
        "uncertain": STATUS_UNCERTAIN,
        "unknown": STATUS_UNCERTAIN,
        "skip": STATUS_SKIP,
    }
    if status in status_aliases:
        return status_aliases[status]

    # Compatibility with trial annotations generated by the earlier interface.
    judgement = str(record.get("scene_judgement", ""))
    if judgement in {"存在一个主要对象", "多个对象共同影响"}:
        return STATUS_ACTORS if selected_actor_ids(record) else STATUS_INVALID
    if judgement == "无关键对象":
        return STATUS_NONE
    if judgement == "无法判断":
        return STATUS_UNCERTAIN
    if judgement == "跳过":
        return STATUS_SKIP

    if selected_actor_ids(record):
        return STATUS_ACTORS
    return STATUS_INVALID


def _set_similarity(a: Set[str], b: Set[str]) -> Tuple[float, float]:
    if not a and not b:
        return 1.0, 1.0
    union = a | b
    intersection = a & b
    jaccard = len(intersection) / len(union) if union else 1.0
    denominator = len(a) + len(b)
    set_f1 = 2.0 * len(intersection) / denominator if denominator else 1.0
    return jaccard, set_f1


def pairwise_agreement(records: Sequence[Dict[str, Any]]) -> Dict[str, float]:
    by_sample: Dict[str, List[Dict[str, Any]]] = defaultdict(list)
    for record in records:
        sample_id = str(record.get("sample_id", ""))
        if sample_id:
            by_sample[sample_id].append(record)

    status_total = 0
    status_match = 0
    actor_pair_count = 0
    exact_set_match = 0
    jaccard_sum = 0.0
    set_f1_sum = 0.0

    for sample_records in by_sample.values():
        for a, b in combinations(sample_records, 2):
            a_status = annotation_status(a)
            b_status = annotation_status(b)
            if a_status not in {STATUS_SKIP, STATUS_INVALID} and b_status not in {
                STATUS_SKIP,
                STATUS_INVALID,
            }:
                status_total += 1
                if a_status == b_status:
                    status_match += 1

            # Actor-set agreement treats "none" as an empty set and excludes
            # uncertain/skip records because they are not positive or negative labels.
            if a_status not in {STATUS_ACTORS, STATUS_NONE} or b_status not in {
                STATUS_ACTORS,
                STATUS_NONE,
            }:
                continue
            a_ids = set(selected_actor_ids(a))
            b_ids = set(selected_actor_ids(b))
            actor_pair_count += 1
            if a_ids == b_ids:
                exact_set_match += 1
            jaccard, set_f1 = _set_similarity(a_ids, b_ids)
            jaccard_sum += jaccard
            set_f1_sum += set_f1

    exact_set_agreement = (
        exact_set_match / actor_pair_count if actor_pair_count else float("nan")
    )
    return {
        "pairwise_status_agreement": (
            status_match / status_total if status_total else float("nan")
        ),
        "pairwise_exact_set_agreement": exact_set_agreement,
        "pairwise_mean_jaccard": (
            jaccard_sum / actor_pair_count if actor_pair_count else float("nan")
        ),
        "pairwise_mean_set_f1": (
            set_f1_sum / actor_pair_count if actor_pair_count else float("nan")
        ),
        "status_pair_count": status_total,
        "actor_set_pair_count": actor_pair_count,
        # Backward-compatible alias used by the original smoke test/output reader.
        "pairwise_exact_agreement": exact_set_agreement,
    }


def krippendorff_alpha_binary(
    records: Sequence[Dict[str, Any]],
    manifest_samples: Sequence[Dict[str, Any]],
) -> float:
    """Nominal Krippendorff alpha over per-sample, per-actor binary decisions.

    Each candidate actor in the manifest is a unit. A decisive annotator assigns
    1 when selecting that actor and 0 otherwise. Uncertain and skipped records are
    treated as missing values rather than negative labels.
    """
    by_sample: Dict[str, List[Dict[str, Any]]] = defaultdict(list)
    for record in records:
        sample_id = str(record.get("sample_id", ""))
        if sample_id and annotation_status(record) in {STATUS_ACTORS, STATUS_NONE}:
            by_sample[sample_id].append(record)

    observed_disagreements = 0
    observed_pairs = 0
    all_ratings: List[int] = []

    for sample in manifest_samples:
        sample_id = str(sample.get("sample_id", ""))
        sample_records = by_sample.get(sample_id, [])
        if len(sample_records) < 2:
            continue
        candidate_ids = {
            str(actor.get("actor_id"))
            for actor in sample.get("candidates", [])
            if actor.get("actor_id") is not None
        }
        for actor_id in candidate_ids:
            ratings = [
                1 if actor_id in set(selected_actor_ids(record)) else 0
                for record in sample_records
            ]
            if len(ratings) < 2:
                continue
            count_one = sum(ratings)
            count_zero = len(ratings) - count_one
            observed_disagreements += count_one * count_zero
            observed_pairs += len(ratings) * (len(ratings) - 1) // 2
            all_ratings.extend(ratings)

    if observed_pairs == 0 or not all_ratings:
        return float("nan")
    observed = observed_disagreements / observed_pairs
    p_one = sum(all_ratings) / len(all_ratings)
    p_zero = 1.0 - p_one
    expected = 1.0 - (p_one * p_one + p_zero * p_zero)
    if expected <= 1e-12:
        return float("nan")
    return 1.0 - observed / expected


def build_consensus(
    records: Sequence[Dict[str, Any]],
    threshold: float = 0.5,
) -> List[Dict[str, Any]]:
    if not 0.0 <= threshold < 1.0:
        raise ValueError("consensus threshold 必须位于 [0, 1) 范围内")

    by_sample: Dict[str, List[Dict[str, Any]]] = defaultdict(list)
    for record in records:
        sample_id = str(record.get("sample_id", ""))
        if sample_id and annotation_status(record) not in {STATUS_SKIP, STATUS_INVALID}:
            by_sample[sample_id].append(record)

    consensus: List[Dict[str, Any]] = []
    for sample_id, sample_records in sorted(by_sample.items()):
        decisive_records = [
            record
            for record in sample_records
            if annotation_status(record) in {STATUS_ACTORS, STATUS_NONE}
        ]
        uncertain_count = sum(
            annotation_status(record) == STATUS_UNCERTAIN for record in sample_records
        )
        none_count = sum(
            annotation_status(record) == STATUS_NONE for record in decisive_records
        )
        n_total = len(sample_records)
        n_decisive = len(decisive_records)

        actor_votes: Counter[str] = Counter()
        for record in decisive_records:
            for actor_id in set(selected_actor_ids(record)):
                actor_votes[actor_id] += 1

        actor_vote_ratios = {
            actor_id: votes / n_decisive
            for actor_id, votes in actor_votes.items()
            if n_decisive
        }
        consensus_actor_ids = sorted(
            [
                actor_id
                for actor_id, ratio in actor_vote_ratios.items()
                if ratio > threshold
            ],
            key=lambda actor_id: (-actor_votes[actor_id], actor_id),
        )

        top_actor_id: Optional[str] = None
        top_actor_votes = 0
        top_actor_tied = False
        if actor_votes:
            top_actor_id, top_actor_votes = actor_votes.most_common(1)[0]
            top_actor_tied = (
                sum(1 for votes in actor_votes.values() if votes == top_actor_votes) > 1
            )
        consensus_primary_actor_id = (
            top_actor_id
            if top_actor_id in consensus_actor_ids and not top_actor_tied
            else None
        )

        none_ratio = none_count / n_decisive if n_decisive else 0.0
        uncertain_ratio = uncertain_count / n_total if n_total else 0.0
        if uncertain_ratio > threshold:
            consensus_status = STATUS_UNCERTAIN
        elif consensus_actor_ids:
            consensus_status = STATUS_ACTORS
        elif none_ratio > threshold:
            consensus_status = STATUS_NONE
        else:
            consensus_status = "no_consensus"

        confidences = [
            float(record.get("confidence"))
            for record in sample_records
            if record.get("confidence") is not None
        ]
        needs_adjudication = bool(
            n_decisive < 2
            or consensus_status in {STATUS_UNCERTAIN, "no_consensus"}
        )
        consensus.append(
            {
                "sample_id": sample_id,
                "n_annotators": n_total,
                "n_decisive_annotators": n_decisive,
                "consensus_threshold": threshold,
                "consensus_status": consensus_status,
                "consensus_actor_ids": consensus_actor_ids,
                "consensus_primary_actor_id": consensus_primary_actor_id,
                # Alias retained for compatibility with older result readers.
                "consensus_actor_id": consensus_primary_actor_id,
                "actor_vote_counts": dict(sorted(actor_votes.items())),
                "actor_vote_ratios": dict(sorted(actor_vote_ratios.items())),
                "primary_actor_votes": top_actor_votes,
                "primary_actor_vote_ratio": (
                    top_actor_votes / n_decisive if n_decisive else 0.0
                ),
                "primary_actor_tied": top_actor_tied,
                "none_votes": none_count,
                "none_vote_ratio": none_ratio,
                "uncertain_votes": uncertain_count,
                "uncertain_vote_ratio": uncertain_ratio,
                "mean_confidence": (
                    sum(confidences) / len(confidences) if confidences else None
                ),
                "needs_adjudication": needs_adjudication,
            }
        )
    return consensus


def _nested_get(data: Dict[str, Any], dotted: str) -> Any:
    current: Any = data
    for part in dotted.split("."):
        if not isinstance(current, dict) or part not in current:
            return None
        current = current[part]
    return current


def _extract_actor_id(value: Any) -> Optional[str]:
    if value is None:
        return None
    if isinstance(value, dict):
        for key in ["actor_id", "id", "selected_actor_id", "critical_actor_id"]:
            if value.get(key) is not None:
                return str(value[key])
        return None
    if isinstance(value, (str, int)):
        return str(value)
    return None


def prediction_actor_id(record: Dict[str, Any]) -> Optional[str]:
    for key in [
        "selected_actor_id",
        "critical_actor_id",
        "causal_actor_id",
        "primary_actor_id",
        "actor_id",
        "causal_object.id",
        "critical_actor.id",
        "label.causal_object.id",
        "result.causal_object.id",
    ]:
        actor_id = _extract_actor_id(_nested_get(record, key))
        if actor_id is not None:
            return actor_id
    return None


def _actor_id_list(value: Any) -> List[str]:
    if not isinstance(value, (list, tuple)):
        return []
    result: List[str] = []
    for item in value:
        actor_id = _extract_actor_id(item)
        if actor_id is not None and actor_id not in result:
            result.append(actor_id)
    return result


def prediction_candidate_actor_ids(record: Dict[str, Any]) -> List[str]:
    for key in [
        "candidate_actor_ids",
        "top_candidate_actor_ids",
        "analysis_candidate_actor_ids",
        "topk_actor_ids",
        "ranked_actor_ids",
        "candidates",
        "candidate_actors",
        "ranked_candidates",
        "result.candidates",
        "result.candidate_actors",
    ]:
        values = _actor_id_list(_nested_get(record, key))
        if values:
            return values
    return []


def compare_predictions(
    consensus: Sequence[Dict[str, Any]],
    prediction_records: Sequence[Dict[str, Any]],
    candidate_k: int = 3,
) -> Dict[str, Any]:
    if candidate_k <= 0:
        raise ValueError("candidate_k 必须大于 0")

    predictions: Dict[str, Dict[str, Any]] = {}
    for record in prediction_records:
        sample_id = str(record.get("sample_id", ""))
        if sample_id:
            predictions[sample_id] = record

    hit_eligible = 0
    hit_correct = 0
    strict_eligible = 0
    strict_correct = 0
    candidate_recall_eligible = 0
    candidate_recall_sum = 0.0
    missing_prediction_records = 0
    missing_primary_actor = 0
    sample_results: List[Dict[str, Any]] = []
    disagreements: List[Dict[str, Any]] = []

    for item in consensus:
        if item.get("consensus_status") != STATUS_ACTORS:
            continue
        human_set = {
            str(actor_id) for actor_id in item.get("consensus_actor_ids", [])
        }
        if not human_set or int(item.get("n_decisive_annotators", 0)) < 2:
            continue

        sample_id = str(item["sample_id"])
        hit_eligible += 1
        prediction = predictions.get(sample_id)
        predicted_primary: Optional[str] = None
        candidate_ids: List[str] = []
        reason = ""
        if prediction is None:
            missing_prediction_records += 1
            reason = "missing_prediction_record"
        else:
            predicted_primary = prediction_actor_id(prediction)
            candidate_ids = prediction_candidate_actor_ids(prediction)
            if predicted_primary is None:
                missing_primary_actor += 1
                reason = "missing_primary_actor"

        primary_hit = bool(
            predicted_primary is not None and predicted_primary in human_set
        )
        if primary_hit:
            hit_correct += 1
        elif not reason:
            reason = "primary_actor_not_in_human_consensus_set"

        human_primary = item.get("consensus_primary_actor_id")
        strict_match: Optional[bool] = None
        if human_primary is not None:
            strict_eligible += 1
            strict_match = bool(
                predicted_primary is not None
                and str(predicted_primary) == str(human_primary)
            )
            if strict_match:
                strict_correct += 1

        candidate_recall: Optional[float] = None
        if candidate_ids:
            topk = set(candidate_ids[:candidate_k])
            candidate_recall = len(topk & human_set) / len(human_set)
            candidate_recall_eligible += 1
            candidate_recall_sum += candidate_recall

        result = {
            "sample_id": sample_id,
            "human_consensus_actor_ids": sorted(human_set),
            "human_primary_actor_id": human_primary,
            "predicted_primary_actor_id": predicted_primary,
            "primary_actor_hit": primary_hit,
            "strict_top1_match": strict_match,
            "candidate_k": candidate_k,
            "prediction_candidate_actor_ids": candidate_ids[:candidate_k],
            "candidate_recall_at_k": candidate_recall,
            "reason": reason,
        }
        sample_results.append(result)
        if reason:
            disagreements.append(result)

    return {
        "eligible_human_actor_samples": hit_eligible,
        "primary_actor_hits": hit_correct,
        "human_consensus_hit_rate": (
            hit_correct / hit_eligible if hit_eligible else float("nan")
        ),
        "strict_top1_eligible_samples": strict_eligible,
        "strict_top1_correct": strict_correct,
        "strict_top1_accuracy": (
            strict_correct / strict_eligible if strict_eligible else float("nan")
        ),
        "candidate_k": candidate_k,
        "candidate_recall_at_k_eligible_samples": candidate_recall_eligible,
        "candidate_recall_at_k": (
            candidate_recall_sum / candidate_recall_eligible
            if candidate_recall_eligible
            else float("nan")
        ),
        "missing_prediction_records": missing_prediction_records,
        "missing_primary_actor": missing_primary_actor,
        "sample_results": sample_results,
        "disagreements": disagreements,
    }


def write_csv(path: Path, rows: Sequence[Dict[str, Any]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if not rows:
        path.write_text("", encoding="utf-8")
        return
    fields = sorted({key for row in rows for key in row.keys()})
    with path.open("w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fields)
        writer.writeheader()
        for row in rows:
            serialized = {}
            for key, value in row.items():
                if isinstance(value, (list, dict)):
                    serialized[key] = json.dumps(value, ensure_ascii=False)
                else:
                    serialized[key] = value
            writer.writerow(serialized)
